### ISSUE TITLE
Add kadanes Algorithm to the Project

### ISSUE THREAD

**Issue by 2021eo3ar** [mojoece/cpp_#1]
I would like to add the Kadanes algorithm problem statement with solution, please assign me this issue with hactoberfest label

**Comment by mojoece** [comment]
I have assigned this issue to you.

**Comment by 2021eo3ar** [comment]
Hey @mo-jo-dev I have raised a PR , Kindly merger it

**Comment by mojoece** [comment]
Hi @2021eo3ar thank you for your code. The code is now merged.

**Comment by 2021eo3ar** [comment]
but it is not being counted in hactober fest
